source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'

  gem 'byebug'
  gem 'pry-rails'
end

group :test do
  gem 'capybara'
  gem 'shoulda-matchers', '~>3.1'
  gem 'faker'
  gem 'launchy'
end

group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'web-console', '>= 3.3.0'
  gem 'spring'
  gem 'listen'
end
